### ISSUE TITLE
distribution cli: E character missing in result file

### ISSUE THREAD

**Issue by IvanHeriver** [benRenard/BMSL#4]
In some cases, the result file of the distribution utility contains invalid number because "E" character is missing e.g. `0.195190749388099-303` instead of `0.195190749388099E-303`. 
Only very small numbers seem to be affected. 

To reproduce the bug, run the following command (with windows 11 at least, might be OS specific):

```
distribution -name Gaussian -par 0,1 -act d -x -100,100,100
```

Any idea why @benRenard ?

**Comment by benRenard** [comment]
Fixed using 'E3' in format specification as suggested [here](https://stackoverflow.com/questions/24004824/for-three-digit-exponents-fortran-drops-the-e-in-the-output)
